spring.application.name=CartService
server.port=8002
eureka.client.service-url.defaultZone = http://localhost:9000/eureka/

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/SkillEx2
spring.datasource.username=postgres
spring.datasource.password=Opj@2006


#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update